# Generated by Django 5.1.3 on 2024-12-05 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('is_individual_person', models.BooleanField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_api.region')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_api.questiontype')),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_api.usertype')),
            ],
        ),
    ]
